language: java
install:
- mvn clean package
deploy:
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
  region: us-east-1
  app: Recap-Harvester
  env: nightly-recap-harvester-production
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: recap-harvester-production
  on:
    repo: NYPL/recap-harvester
    branch: production
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_QA"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_QA"
  region: us-east-1
  app: Recap-Harvester
  env: nightly-recap-harvester-qa
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: recap-harvester-qa
  on:
    repo: NYPL/recap-harvester
    branch: qa
env:
  global:
    secure: 7qwWAfwLkwg9ptWOKi/MatheTNo93+WwEUt4rfbHd1KB9Rk/ch9QkgBi23TaYHXqs9ppNkaSeEQtiukhH3JZrmpVRdYhb7NCC+sByinTgFD7QuhjHj8gLCST+uIkvp7bcfMyCSvdlEWbrs6bA8ca4p5ybv3K92YzUIbFTV2x1sjK/dDZYd1RJARbkKXr0oBO+L/9d3XymjzpSYmVQ0hJQlUlT31Zf/BNKTGikgbYiw2IKWqp65dQ+nJ3CK5fxmMPkDJ8oe8wgKRK0LHTktqf7SfAHRboDjwC+bQrgSfVeHyGxDXrx7ziS0fQv7CP2ohrdBNrggF1zRgKpcf6AP9zj8tdNldZYwx8qsOF7SURMak6CDJe3IynvjQaQoGkd+g+aUP43Qb1fXu2qLqjR099bwkksDGVoWnFVIXOCuPvE56X5fpF8zwyy+JVrP1gvhDCnkviRDErdHjIJ0TWKDoYKhALwKfCgCtuoVzL7Qx+8E1BmMCqWfzMvqLnyLvwPMsydGPCesCfMNumbEJjHDa4zq/owGdCMOwIqQgvh93717W1Nr1V3GIf27n4RxZ7BuHFay0kOKm1JhI/f4yqR5CIu7u7wf+yaJLVFfNikNscS65TY+j4f02RXxReUJrrVEb8C52AKPikeAkKtXym6JOgzYL+0gEG3NpkHhXFWLsQed0=
